ARG PYTHON_VER
ARG PYTHON_ENV
ARG SETUP_FOLDER

# define base image
FROM python:${PYTHON_VER:-3.13}-slim-bookworm AS builder

# see devcontainer.json to see argument values
ARG PYTHON_ENV
ARG SETUP_FOLDER

ENV PYTHON_ENV=$PYTHON_ENV
ENV SETUP_FOLDER=$SETUP_FOLDER

# create directory
RUN mkdir $SETUP_FOLDER

# copy files
COPY linux-updates.sh py_pkg_install.sh pypkgs.txt /$SETUP_FOLDER/

# setup environment
RUN bash ./${SETUP_FOLDER}/linux-updates.sh
RUN bash ./${SETUP_FOLDER}/py_pkg_install.sh $PYTHON_ENV $SETUP_FOLDER

# expose port
EXPOSE 8888

# final stage
FROM python:${PYTHON_VER:-3.13}-slim-bookworm

ARG PYTHON_ENV
ENV PYTHON_ENV=${PYTHON_ENV}

COPY --from=builder /opt/${PYTHON_ENV} /opt/${PYTHON_ENV}

# expose port
EXPOSE 8888
ENV PATH="/opt/${PYTHON_ENV}/bin:$PATH"

SHELL ["/bin/bash", "-c"]
